package com.jsm.forum.model;

import com.jsm.forum.model.base.BaseBasicUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicUser extends BaseBasicUser<BasicUser> {
	public static final BasicUser dao = new BasicUser().dao();
}
