package com.jsm.forum.model;

import com.jsm.forum.model.base.BaseChildComments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChildComments extends BaseChildComments<ChildComments> {
	public static final ChildComments dao = new ChildComments().dao();
}
