package com.jsm.forum.model;

import com.jsm.forum.model.base.BaseForumPosts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ForumPosts extends BaseForumPosts<ForumPosts> {
	public static final ForumPosts dao = new ForumPosts().dao();
}
