package com.jsm.forum.model;

import com.jsm.forum.model.base.BaseILikeTheArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ILikeTheArticle extends BaseILikeTheArticle<ILikeTheArticle> {
	public static final ILikeTheArticle dao = new ILikeTheArticle().dao();
}
