package com.jsm.forum.model;

import com.jsm.forum.model.base.BaseILikeTheComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ILikeTheComment extends BaseILikeTheComment<ILikeTheComment> {
	public static final ILikeTheComment dao = new ILikeTheComment().dao();
}
