package com.jsm.forum.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseForumPosts<M extends BaseForumPosts<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setCover(java.lang.String cover) {
		set("cover", cover);
		return (M)this;
	}

	public java.lang.String getCover() {
		return getStr("cover");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setIsShow(java.lang.Integer isShow) {
		set("isShow", isShow);
		return (M)this;
	}

	public java.lang.Integer getIsShow() {
		return getInt("isShow");
	}

	public M setPraise(java.lang.Integer praise) {
		set("praise", praise);
		return (M)this;
	}

	public java.lang.Integer getPraise() {
		return getInt("praise");
	}

	public M setTrample(java.lang.Integer trample) {
		set("trample", trample);
		return (M)this;
	}

	public java.lang.Integer getTrample() {
		return getInt("trample");
	}

	public M setLookTime(java.lang.Integer lookTime) {
		set("look_time", lookTime);
		return (M)this;
	}

	public java.lang.Integer getLookTime() {
		return getInt("look_time");
	}

	public M setCreateDate(java.lang.String createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.lang.String getCreateDate() {
		return getStr("create_date");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return getStr("text");
	}

}
