package com.jsm.forum.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBasicUser<M extends BaseBasicUser<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setHeadImg(java.lang.String headImg) {
		set("head_Img", headImg);
		return (M)this;
	}

	public java.lang.String getHeadImg() {
		return getStr("head_Img");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setIntro(java.lang.String intro) {
		set("intro", intro);
		return (M)this;
	}

	public java.lang.String getIntro() {
		return getStr("intro");
	}

}
